#cloud-config
write_files:
  - path: /tmp/id_rsa.temp
    permissions: '0600'
    encoding: b64
    content: ${private_key}

runcmd:
  - setenforce 0
  - sudo grubby --update-kernel ALL --args selinux=0

  - sed -i 's|^mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/rocky*.repo
  - sed -i 's|^#baseurl=http://dl.rockylinux.org/$contentdir|baseurl=http://mirror.navercorp.com/rocky|g' /etc/yum.repos.d/rocky*.repo

  - mkdir -p /home/${username}/.ssh
  - mv /tmp/id_rsa.temp /home/${username}/.ssh/id_rsa
  - chown -R ${username}:${username} /home/${username}/.ssh
  - chmod 700 /home/${username}/.ssh
  - chmod 600 /home/${username}/.ssh/id_rsa
  
  - echo "SSH Key setup completed for ${username}" >> /var/log/cloud-init-custom.log
  - ls -la /home/${username}/.ssh >> /var/log/cloud-init-custom.log